version: "3"

services:
  mongo1:
    restart: always
    environment:
      - MONGO_ROLE=primary
      - MONGO_SECONDARY=mongo2:27017
      - MONGO_ARBITER=mongo3:27017
    tty: true
    hostname: mongo1
    image: thanhlcm90/mongo-rep-set:latest
    stdin_open: true
    networks:
      main:
        aliases:
          - mongo1

  mongo2:
    restart: always
    tty: true
    hostname: mongo2
    image: thanhlcm90/mongo-rep-set:latest
    stdin_open: true
    networks:
      main:
        aliases:
          - mongo2

  mongo3:
    restart: always
    environment:
      - JOURNALING=no
    tty: true
    hostname: mongo3
    image: thanhlcm90/mongo-rep-set:latest
    stdin_open: true
    networks:
      main:
        aliases:
          - mongo3

networks:
  main:
